import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Compound from "@compound-finance/compound-js";
import calculateAPY from "../apy.js";

export async function getServerSideProps(context) {
  const apys = await Promise.all([
    calculateAPY(Compound.cDAI, "DAI"),
    calculateAPY(Compound.cUSDC, "USDC"),
    calculateAPY(Compound.cUSDT, "USDT"),
  ]);

  return {
    props: {
      apys,
    },
  };
}

export default function Home({ apys }) {
  const formatPercent = number => {
    return `${new Number(number).toFixed(2)} % `;
  };
  return (
    <div className="container">
      <Head>
        <title>Compound Dashboard</title>
        <meta name="description" content="Generated by Compound Dashboard" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="row mt-4">
        <div className="col-sm-12">
          <div className="jumbotron">
            <h1 className="text-center">Compound Dashboard</h1>
            <h5 className="display-4 text-center">
              Shows Compound APYs <br /> with COMP token rewards
            </h5>
          </div>
        </div>
      </div>

      <table className="table">
        <thead>
          <tr>
            <th>Ticker</th>
            <th>Supply APY</th>
            <th>COMP APY</th>
            <th>Total APY</th>
          </tr>
        </thead>
        <tbody>
          {apys &&
            apys.map((apy, index) => (
              <tr key={index}>
                <td
                  style={{
                    width: "30%",
                  }}
                >
                  <Image
                    src={`/img/${apy.ticker.toLowerCase()}.png`}
                    alt="ticker image"
                    width="20px"
                    height="20px"
                  />
                  <span
                    style={{
                      marginLeft: "10px",
                      lineHeight: "20px",
                      fontSize: "20px",
                    }}
                  >
                    {apy.ticker.toUpperCase()}
                  </span>
                </td>
                <td>{formatPercent(apy.supplyApy)}</td>
                <td>{formatPercent(apy.compApy)}</td>
                <td>
                  {formatPercent(
                    parseFloat(apy.supplyApy) + parseFloat(apy.compApy)
                  )}
                </td>
              </tr>
            ))}
        </tbody>
      </table>
    </div>
  );
}
